name: Run Tests
env:
  PIP_CACHE_DIR: .pip
  PYTHONPATH: src
on:
  push:
    paths:
      - ".github/workflows/tests.yml"
      - "docs/**"
      - "**.md"
      - "**.py"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "scripts/**"
      - "webfonts/**"
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types: ["published"]
jobs:
  build-push:
    name: "Build & Push Docs"
    runs-on: ubuntu-24.04
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # Cache dependencies
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ./.pip
          key: ${{ runner.os }}-docs-${{ hashFiles('requirements.txt') }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v1

      # Install dependencies
      - name: Install Dependencies
        run: |
          uv pip install --system -e .[lint,test]

      - name: Install NodeJS
        uses: actions/setup-node@v6

      - name: Install SASS
        run: npm install -g sass

      - name: Build
        run: ./scripts/build --target=test

      - name: Test
        run: pytest tests/
